-- =====================================================
-- Seed Data: educational_content.modules
-- Description: Módulos educativos base de comprensión lectora
-- Records: 4
-- Created: 2025-10-27
-- =====================================================

SET search_path TO educational_content, public;

TRUNCATE TABLE educational_content.modules RESTART IDENTITY CASCADE;

INSERT INTO educational_content.modules (
    id, tenant_id, title, subtitle, description, summary, content,
    order_index, module_code, difficulty_level, grade_levels, subjects,
    estimated_duration_minutes, estimated_sessions, learning_objectives,
    competencies, skills_developed, prerequisites, prerequisite_skills,
    maya_rank_required, maya_rank_granted, xp_reward, ml_coins_reward,
    status, is_published, is_featured, is_free, is_demo_module,
    published_at, archived_at, version, version_notes, created_by,
    reviewed_by, approved_by, keywords, tags, thumbnail_url,
    cover_image_url, settings, metadata, created_at, updated_at,
    total_exercises
) VALUES
-- Módulo 1: Comprensión Literal
('11111111-1111-1111-1111-111111111111'::uuid, NULL, 
'Módulo 1: Comprensión Literal', 
'Los primeros pasos en la lectura detectivesca',
'Aprende a identificar información explícita en los textos y desarrolla habilidades básicas de lectura comprensiva.',
NULL,
'{"marie_curie_story": {}, "reading_materials": [], "historical_context": {}, "scientific_concepts": {}, "multimedia_resources": []}'::jsonb,
1, NULL, 'beginner'::difficulty_level,
ARRAY['6','7','8']::text[], ARRAY['Literatura','Ciencias']::text[],
120, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
100, 50, 'published'::content_status, true, false, true, false,
NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
'{}'::jsonb, '{}'::jsonb,
'2025-10-16T09:05:38.53792-06:00'::timestamp with time zone,
'2025-10-16T09:05:38.53792-06:00'::timestamp with time zone,
0),

-- Módulo 2: Comprensión Inferencial
('11111111-1111-1111-1111-111111111112'::uuid, NULL,
'Módulo 2: Comprensión Inferencial',
NULL,
'Desarrolla habilidades para entender lo que no se dice explícitamente.',
NULL,
'{"marie_curie_story": {}, "reading_materials": [], "historical_context": {}, "scientific_concepts": {}, "multimedia_resources": []}'::jsonb,
2, NULL, 'intermediate'::difficulty_level,
ARRAY['6','7','8']::text[], ARRAY['Literatura','Ciencias']::text[],
150, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
150, 75, 'draft'::content_status, true, false, true, false,
NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
'{}'::jsonb, '{}'::jsonb,
'2025-10-16T08:46:24.599287-06:00'::timestamp with time zone,
'2025-10-16T08:46:24.599287-06:00'::timestamp with time zone,
0),

-- Módulo 3: Comprensión Crítica
('11111111-1111-1111-1111-111111111113'::uuid, NULL,
'Módulo 3: Comprensión Crítica',
NULL,
'Analiza y evalúa textos críticamente.',
NULL,
'{"marie_curie_story": {}, "reading_materials": [], "historical_context": {}, "scientific_concepts": {}, "multimedia_resources": []}'::jsonb,
3, NULL, 'advanced'::difficulty_level,
ARRAY['6','7','8']::text[], ARRAY['Literatura','Ciencias']::text[],
180, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
200, 100, 'draft'::content_status, true, false, true, false,
NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
'{}'::jsonb, '{}'::jsonb,
'2025-10-16T08:46:24.599287-06:00'::timestamp with time zone,
'2025-10-16T08:46:24.599287-06:00'::timestamp with time zone,
0),

-- Módulo 4: Lectura Digital
('11111111-1111-1111-1111-111111111114'::uuid, NULL,
'Módulo 4: Lectura Digital',
NULL,
'Domina la lectura en medios digitales.',
NULL,
'{"marie_curie_story": {}, "reading_materials": [], "historical_context": {}, "scientific_concepts": {}, "multimedia_resources": []}'::jsonb,
4, NULL, 'intermediate'::difficulty_level,
ARRAY['6','7','8']::text[], ARRAY['Literatura','Ciencias']::text[],
160, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
180, 90, 'draft'::content_status, true, false, true, false,
NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
'{}'::jsonb, '{}'::jsonb,
'2025-10-16T08:46:24.599287-06:00'::timestamp with time zone,
'2025-10-16T08:46:24.599287-06:00'::timestamp with time zone,
0)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    summary = EXCLUDED.summary,
    content = EXCLUDED.content,
    order_index = EXCLUDED.order_index,
    module_code = EXCLUDED.module_code,
    difficulty_level = EXCLUDED.difficulty_level,
    grade_levels = EXCLUDED.grade_levels,
    subjects = EXCLUDED.subjects,
    estimated_duration_minutes = EXCLUDED.estimated_duration_minutes,
    estimated_sessions = EXCLUDED.estimated_sessions,
    learning_objectives = EXCLUDED.learning_objectives,
    competencies = EXCLUDED.competencies,
    skills_developed = EXCLUDED.skills_developed,
    prerequisites = EXCLUDED.prerequisites,
    prerequisite_skills = EXCLUDED.prerequisite_skills,
    maya_rank_required = EXCLUDED.maya_rank_required,
    maya_rank_granted = EXCLUDED.maya_rank_granted,
    xp_reward = EXCLUDED.xp_reward,
    ml_coins_reward = EXCLUDED.ml_coins_reward,
    status = EXCLUDED.status,
    is_published = EXCLUDED.is_published,
    is_featured = EXCLUDED.is_featured,
    is_free = EXCLUDED.is_free,
    is_demo_module = EXCLUDED.is_demo_module,
    published_at = EXCLUDED.published_at,
    archived_at = EXCLUDED.archived_at,
    version = EXCLUDED.version,
    version_notes = EXCLUDED.version_notes,
    created_by = EXCLUDED.created_by,
    reviewed_by = EXCLUDED.reviewed_by,
    approved_by = EXCLUDED.approved_by,
    keywords = EXCLUDED.keywords,
    tags = EXCLUDED.tags,
    thumbnail_url = EXCLUDED.thumbnail_url,
    cover_image_url = EXCLUDED.cover_image_url,
    settings = EXCLUDED.settings,
    metadata = EXCLUDED.metadata,
    updated_at = EXCLUDED.updated_at,
    total_exercises = EXCLUDED.total_exercises;
